app = "shogikaisetukun"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"
  builder = "paketobuildpacks/builder:base"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

[env]
RAILS_ENV = "production"

[[statics]]
guest_path = "/usr/share/nginx/html"
url_prefix = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
