app = "shogikaisetukun-api"
primary_region = "nrt"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25

  [[services.ports]]
    handlers = ["http"]
    port = 3000

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
