app = "shogikaisetukun"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[env]
RAILS_ENV = "production"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
